{
 "title": "All info in one place Copy",
 "time": { "from": "2023-03-12T10:01:22.000Z", "to": "now" },
 "panels": [
  { "title": "Backend info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Info",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_requests_total[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(http_requests_total[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU usage per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} )  / (node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) ))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}